#!/bin/bash

set -x

lsof -i:9999| grep java | awk '{print $2}'| xargs kill

THREADS=1
TARGETRATE=100
PORT=9999
CYCLES=100000000

cd ebdse && nohup /tmp/ebdse/ebdse -v run type=tcpserver yaml=simple tags=phase:main port="$PORT" cycles="$CYCLES" threads="$THREADS" targetrate="$TARGETRATE" &
